name: attendance

on:
  schedule:
    - cron: '15 17 * * *'
  workflow_dispatch:
  workflow_call:
    secrets:
      SKLAND_TOKENS:
        required: true
      SKLAND_NOTIFICATION_URLS:
        required: false
      SKLAND_ANONYMOUS:
        required: false
      MAX_RETRIES:
        required: false
    inputs:
      repository:
        description: The repository to run the workflow on
        default: enpitsuLin/skland-daily-attendance
        required: false
        type: string

jobs:
  attendance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          repository: ${{ inputs.repository || github.repository }}

      - name: Install pnpm
        # uses: pnpm/action-setup@v4
        # with:
        #   run_install: false
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_wait_seconds: 10
          command: npm install -g pnpm

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.13.0
          cache: 'pnpm'
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: Install dependencies
        # run: pnpm install
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 10
          max_attempts: 3
          command: pnpm install

      - name: Run daily attendance
        # run: pnpm action
        uses: nick-fields/retry@v3
        env:
          SKLAND_TOKENS: ${{ secrets.SKLAND_TOKENS }}
          SKLAND_NOTIFICATION_URLS: ${{ secrets.SKLAND_NOTIFICATION_URLS }}
          SKLAND_MAX_RETRIES: ${{ secrets.MAX_RETRIES }}
          SKLAND_ANONYMOUS: ${{ secrets.SKLAND_ANONYMOUS }}
        with:
          timeout_minutes: 10
          max_attempts: 3
          retry_wait_seconds: 10
          command: pnpm action
